version: '3.8'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - my_network
    environment:
      MONGO_HOST: mongodb  
      MONGO_PORT: 27017

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - my_network

networks:
  my_network:
    driver: bridge